name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: dn6poc-travel-func            # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Dn6Poc.TravelFunc' # set this to the path to your web app project, defaults to the repository root ('.')

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName!~Dn6Poc.DocuMgmtPortal.E2ETests

    # Everything looks OK; Now make release build  
    - name: 'Build (Release)'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    # Then login to Azure and deploy it
    # Works; But oh wait, don't deploy first
    # - uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}
    # - name: 'Run Azure Functions Action'
    #   uses: Azure/functions-action@v1
    #   with:
    #     app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
    #     package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
